basic:
  time-zone: Asia/Tehran
  port: 8088
  environment: prod
  #  Environment: dev
  insert-batch-size: 100
  pending-process-batch-size: 1000
  republish-lock-duration: 5

database:
  connection_string: host=arcs-db port=5432 user=admin dbname=arcs password=pass sslmode=disable

redis:
  addr: redis:6379
  password: pass
  db: 0

producer:
  url: nats:4222
  client-timeout: 2
  reconnect-wait: 5
  max-reconnects: -1
  retry-timeout: 10
  stream: sms
  queue: sends
  subjects:
    - senders

order:
  cost-per-dst: 2
