basic:
  time-zone: Asia/Tehran
  port: 8088
  environment: prod
  #  Environment: dev
  insert-batch-size: 300
  pending-process-batch-size: 100
  republish-lock-duration: 5

database:
  connection_string: host=localhost port=5440 user=admin dbname=arcs password=pass sslmode=disable TimeZone=Asia/Tehran

redis:
  addr: localhost:6380
  password: pass
  db: 0

nats:
  url: localhost:4222
  client-timeout: 2
  reconnect-wait: 5
  max-reconnects: -1
  retry-timeout: 10
  stream: sms
  queue: sends
  subjects:
    - senders

order:
  cost-per-dst: 2
