FROM docker.arvancloud.ir/golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
COPY config.yaml /config/config.yaml

RUN go build -o manager ./cmd/manager

FROM docker.arvancloud.ir/alpine:3.22.0

WORKDIR /app

RUN apk add --no-cache tzdata

COPY --from=builder /app/manager ./
COPY --from=builder /config/config.yaml /config/config.yaml

CMD ["./manager"]
