basic:
  time-zone: Asia/Tehran
  #  environment: dev
  environment: prod

database:
  connection_string: host=arcs-db port=5432 user=admin dbname=arcs password=pass sslmode=disable

consumer:
  url: nats:4222
  client-timeout: 2
  reconnect-wait: 2
  max-reconnects: -1
  retry-timeout: 10
  stream: sms
  queue: sends
  subjects:
    - senders

delivery:
  success-rate: 80
  buffer-flush-interval: 1500