basic:
  time-zone: Asia/Tehran
  #  environment: dev
  environment: prod

database:
  connection_string: host=localhost port=5440 user=admin dbname=arcs password=pass sslmode=disable TimeZone=Asia/Tehran

consumer:
  url: localhost:4222
  client-timeout: 2
  reconnect-wait: 2
  max-reconnects: -1
  retry-timeout: 10
  stream: sms
  queue: sends
  subjects:
    - senders

delivery:
  success-rate: 50
  buffer-flush-interval: 60