database:
  connection_string: host=localhost port=5440 user=admin dbname=arcs password=pass sslmode=disable TimeZone=Asia/Tehran

nats:
  url: localhost:4222
  client-timeout: 5
  reconnect-wait: 3
  max-reconnects: 3
  retry-timeout: 10
  stream: sms
  queue: sends
  subjects:
    - senders

delivery:
  success-rate: 90